
"""
distillation_trainer.py
Trainer that incorporates Knowledge Distillation (KD).
Uses a TeacherClient to fetch targets (text or logits) and computes combined loss.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from .trainer import Trainer

class DistillationTrainer(Trainer):
    """
    Extends base Trainer to support Knowledge Distillation loops.
    """
    def __init__(self, model, tokenizer, teacher_client, args, device=None):
        super().__init__(model, tokenizer, args, device)
        self.teacher = teacher_client
        self.alpha = getattr(args, 'distill_alpha', 0.5)
        self.temperature = getattr(args, 'distill_temperature', 1.0)
        
    def compute_loss(self, model, inputs, return_outputs=False):
        """
        Modified loss computation:
        Loss = alpha * LM_Loss + (1 - alpha) * KD_Loss
        
        Currently focusing on Text-level distillation because API teachers rarely return full logits.
        If we had logits, we would use KLDiv.
        
        Since we might only get text completions from API:
        Strategy A (Teacher Forcing / Augmentation): 
          - We can't easily compute KLDiv if we don't have teacher logits for the *exact same* tokens at every step.
          - Instead, we often use the teacher to GENERATE data (offline or online) and then train on that data (sequence-level distillation).
        
        If args.distillation_mode == 'sequence':
           - Assume inputs['labels'] are already distilled/generated by teacher?
           - Or are we generating on the fly?
           
        Refining Plan based on "UpdatePlan.txt":
        "Estratégia: para cada prompt... obter saída do teacher (logits ou respostas) e treinar o student para imitar."
        
        Since getting logits from Gemini/OpenAI is hard/impossible for standard users:
        We will assume 'Sequence-Level Knowledge Distillation' (train on teacher's output).
        
        If we DO have logits (e.g. local teacher), we add KLDiv.
        """
        
        # 1. Standard LM Loss (CrossEntropy) against ground truth (or teacher-generated text in dataset)
        outputs = model(inputs)
        shift_logits = outputs[..., :-1, :].contiguous()
        shift_labels = inputs[..., 1:].contiguous()
        
        loss_fct = nn.CrossEntropyLoss()
        lm_loss = loss_fct(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1)
        )
        
        # 2. Logit-based KD (Only if available)
        kd_loss = torch.tensor(0.0, device=self.device)
        
        # NOTE: For this initial implementation, we rely on the dataset having "Teacher-generated" content 
        # OR we rely on a separate data prep step. 
        # Doing online generation (generate -> tokenize -> train) inside the training loop is very slow.
        # But if we must:
        
        # Final combined loss
        # For now, without explicit logits from API, alpha effectively balances 
        # "loss against dataset targets" (which might be from teacher).
        # We obey the alpha param primarily if we add auxiliary losses.
        
        return (lm_loss, outputs) if return_outputs else lm_loss

    # Future extension: override train_epoch to perform generation if mode is 'online_generation'
